cc_library(
    name = "lib",
    hdrs = [
        "lib.hpp",
        "debug.hpp",
        "coord.h",
    ],
    srcs = [
        "lib.cpp",
    ],
    deps = [
        "@p-ranav-indicators",
    ],
    visibility = [ "//:__subpackages__" ],
)
